enabled_features:
  - log_command
  - purging
  - auto_vc_gen
  - polls
  - info_commands
  - economy
  - playlist
  - alchemy
  - leave_messages
  - server_list
log_format: '{feature}: {message}'
bot_owner:
  id: 348083986989449216
  bot_owner_fallback_name: 'hopperelec#3060'
  bot_owner_fallback_icon: 'https://www.hopperelec.co.uk/resources/hopper.png?scale=0.2&padding=30&padding-side=-8&type3D=2&shadow=32&fill=100&outline-width=6&bg=1'

servers:
  847254345267281960:
    name: hopperelec
    invite: zCdEKf9YbG
    log_channel: 847261620206960651
    extra_features:
      - log_command
      - purging
      - auto_vc_gen
      - polls
      - info_commands
      - economy
      - playlist
      - alchemy
      - leave_messages
    feature_configs:
      playlist:
        voice_channel: 847259922822856705
        commands_channel: 847259901281173534
      auto_vc_gen:
        channel_names: ['Off Topic','StockBlock']
      info_commands:
        youtube: 'https://yt.hopperelec.co.uk/'
      alchemy:
        commands_channel: 849274424774754324
        suggestions_channel: 849268967347585074
      economy:
        commands_channel: 847259886290206730
        defaultCash: 10
        defaultBank: 1440
        defaultItems: []
        addons:
          - message_rewards
        addon_configs:
          message_rewards:
            channels: [847260412922953739,847260532826439700,847262054032080916,847259998971101194]
      leave_messages:
        channel: 847255472745611364
        format: '{name}#{discriminator} ({id}) has left the server!'
